Method Not Allowed: /account/create-user/
Heyyyyyyyy
Heyyyyyyyy
Heyyyyyyyy
Heyyyyyyyy
Heyyyyyyyy
Method Not Allowed: /account/create-user/
Heyyyyyyyy
Heyyyyyyyy
Method Not Allowed: /account/create-user/
Method Not Allowed: /account/create-user/
Bad Request: /account/create-user/
Method Not Allowed: /account/create-user/
Method Not Allowed: /account/create-user/
Method Not Allowed: /account/create-user/
Bad Request: /account/create-user/
Not Found: /favicon.ico
Not Found: /favicon.ico
Internal Server Error: /account/create-user/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 50, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 196, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 99, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 508, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 468, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 479, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 505, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/decorators.py", line 49, in handler
    return func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 86, in create_user
    send_mail(
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/mail/__init__.py", line 81, in send_mail
    return mail.send()
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/mail/message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 124, in send_messages
    new_conn_created = self.open()
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 80, in open
    self.connection = self.connection_class(
  File "/usr/lib/python3.9/smtplib.py", line 253, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.9/smtplib.py", line 341, in connect
    (code, msg) = self.getreply()
  File "/usr/lib/python3.9/smtplib.py", line 398, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed
Method Not Allowed: /account/create-user/
Internal Server Error: /account/create-user/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 2014, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'collections.OrderedDict'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 50, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 196, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 99, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 508, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 468, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 479, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 505, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/decorators.py", line 49, in handler
    return func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 86, in create_user
    data = serializer.data
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 255, in data
    self._data = self.to_representation(self.validated_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/fields.py", line 1837, in to_representation
    return method(value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 44, in get_token
    return Token.objects.get(user=obj).key
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 629, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1413, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1431, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1438, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1524, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1554, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1470, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1295, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/lookups.py", line 21, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 2016, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got OrderedDict([('first_name', 'Bemilola'), ('username', 'BemDema23'), ('last_name', 'Demo'), ('password', '11234dd56'), ('email', 'real_pygod@icloud.com'), ('profile', OrderedDict([('phone_number', '11234567811190')]))]).
Method Not Allowed: /account/create-user/
Internal Server Error: /account/create-user/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 2014, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'collections.OrderedDict'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 50, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 196, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 99, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 508, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 468, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 479, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 505, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/decorators.py", line 49, in handler
    return func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 86, in create_user
    data = serializer.data
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 255, in data
    self._data = self.to_representation(self.validated_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/fields.py", line 1837, in to_representation
    return method(value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 44, in get_token
    return Token.objects.get(user=obj).key
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 629, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1413, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1431, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1438, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1524, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1554, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1470, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1295, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/lookups.py", line 21, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 2016, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got OrderedDict([('first_name', 'Bemilola'), ('username', 'BemDem0ab'), ('last_name', 'Demo'), ('password', '11234dd56'), ('email', 'real_pygod@icloud.com'), ('profile', OrderedDict([('phone_number', '11234567811190')]))]).
Method Not Allowed: /account/create-user/
Internal Server Error: /account/create-user/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 2014, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'collections.OrderedDict'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 50, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 196, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 99, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 508, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 468, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 479, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 505, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/decorators.py", line 49, in handler
    return func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 86, in create_user
    data = serializer.data
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 255, in data
    self._data = self.to_representation(self.validated_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/fields.py", line 1837, in to_representation
    return method(value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 44, in get_token
    return Token.objects.get(user=obj).key
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 629, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1413, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1431, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1438, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1524, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1554, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1470, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1295, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/lookups.py", line 21, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 2016, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got OrderedDict([('first_name', 'Bemilola'), ('username', 'BemDema28'), ('last_name', 'Demo'), ('password', '11234dd56'), ('email', 'real_pygod@icloud.com'), ('profile', OrderedDict([('phone_number', '11234567811190')]))]).
Method Not Allowed: /account/create-user/
Internal Server Error: /account/create-user/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 2014, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'collections.OrderedDict'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 50, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 196, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 99, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 508, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 468, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 479, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 505, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/decorators.py", line 49, in handler
    return func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 86, in create_user
    data = serializer.data
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 255, in data
    self._data = self.to_representation(self.validated_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/fields.py", line 1837, in to_representation
    return method(value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 44, in get_token
    return Token.objects.get(user=obj).key
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 629, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1413, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1431, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1438, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1524, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1554, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1470, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1295, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/lookups.py", line 21, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 2016, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got OrderedDict([('first_name', 'Bemilola'), ('username', 'BemDemfea'), ('last_name', 'Demo'), ('password', '11234dd56'), ('email', 'real_pygod@icloud.com'), ('profile', OrderedDict([('phone_number', '11234567811190')]))]).
Method Not Allowed: /account/create-user/
Internal Server Error: /account/create-user/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 2014, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'collections.OrderedDict'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 50, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 196, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 99, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 508, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 468, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 479, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 505, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/decorators.py", line 49, in handler
    return func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 86, in create_user
    data = serializer.data
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 255, in data
    self._data = self.to_representation(self.validated_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/fields.py", line 1837, in to_representation
    return method(value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 45, in get_token
    return Token.objects.get(user=obj).key
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 629, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1413, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1431, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1438, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1524, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1554, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1470, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1295, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/lookups.py", line 21, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 2016, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got OrderedDict([('first_name', 'Bemilola'), ('username', 'BemDem62b'), ('last_name', 'Demo'), ('password', '11234dd56'), ('email', 'real_pygod@icloud.com'), ('profile', OrderedDict([('phone_number', '11234567811190')]))]).
Method Not Allowed: /account/create-user/
Internal Server Error: /account/create-user/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 2014, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'collections.OrderedDict'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 50, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 196, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 99, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 508, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 468, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 479, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 505, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/decorators.py", line 49, in handler
    return func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 86, in create_user
    data = serializer.data
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 255, in data
    self._data = self.to_representation(self.validated_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/fields.py", line 1837, in to_representation
    return method(value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 45, in get_token
    return Token.objects.get(user=obj).key
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 629, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1413, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1431, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1438, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1524, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1554, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1470, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1295, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/lookups.py", line 21, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 2016, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got OrderedDict([('first_name', 'Bemilola'), ('username', 'BemDem7c5'), ('last_name', 'Demo'), ('password', '11234dd56'), ('email', 'real_pygod@icloud.com'), ('profile', OrderedDict([('phone_number', '11234567811190')]))]).
Method Not Allowed: /account/create-user/
Internal Server Error: /account/create-user/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 2014, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'collections.OrderedDict'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 50, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 196, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 99, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 508, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 468, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 479, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 505, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/decorators.py", line 49, in handler
    return func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 86, in create_user
    data = serializer.data
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 255, in data
    self._data = self.to_representation(self.validated_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/fields.py", line 1837, in to_representation
    return method(value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 48, in get_referrals
    return Profile.objects.get(user=obj).get_recommened_profiles() if Profile.objects.filter(user=obj).exists() else "No referrals"
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1413, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1431, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1438, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1524, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1554, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1470, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1295, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/lookups.py", line 21, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 2016, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got OrderedDict([('first_name', 'Bemilola'), ('username', 'BemDemb49'), ('last_name', 'Demo'), ('password', '11234dd56'), ('email', 'real_pygod@icloud.com'), ('profile', OrderedDict([('phone_number', '11234567811190')]))]).
Method Not Allowed: /account/create-user/
Internal Server Error: /account/create-user/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 50, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 196, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 99, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 508, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 468, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 479, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 505, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/decorators.py", line 49, in handler
    return func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 86, in create_user
    data = serializer.data
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 255, in data
    self._data = self.to_representation(self.validated_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/fields.py", line 1837, in to_representation
    return method(value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 48, in get_referrals
    print(obj.id)
AttributeError: 'collections.OrderedDict' object has no attribute 'id'
Method Not Allowed: /account/create-user/
Method Not Allowed: /account/create-user/
Method Not Allowed: /account/create-user/
Heyyyyyyyy
Internal Server Error: /account/create-user/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 50, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 196, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 99, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 508, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 468, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 479, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 505, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/decorators.py", line 49, in handler
    return func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 107, in create_user
    serializer.save()
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 198, in save
    assert not hasattr(self, '_data'), (
AssertionError: You cannot call `.save()` after accessing `serializer.data`.If you need to access data before committing to the database then inspect 'serializer.validated_data' instead. 
Method Not Allowed: /account/create-user/
Bad Request: /account/create-user/
Heyyyyyyyy
Heyyyyyyyy
Heyyyyyyyy
Not Found: /favicon.ico
Internal Server Error: /core/service/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 50, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 196, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 99, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 508, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 468, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 479, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 505, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/generics.py", line 198, in get
    return self.list(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `description` is not valid for model `Service`.
Not Found: /favicon.ico
Not Found: /get-banks
Internal Server Error: /core/get-banks/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: bank_list() takes 0 positional arguments but 1 was given
Not Found: /product/1/
Not Found: /favicon.ico
Method Not Allowed: /account/change-password/
Not Found: /account/change-password/1
Method Not Allowed: /account/change-password/
Method Not Allowed: /api/token/
Not Found: /account/chnage-password
Unauthorized: /account/change-password/
Method Not Allowed: /account/change-password/
Internal Server Error: /account/change-password
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/middleware/common.py", line 88, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/account/change-password/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
Method Not Allowed: /account/change-password/
Internal Server Error: /account/change-password
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/middleware/common.py", line 88, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/account/change-password/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
Internal Server Error: /account/change-password
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/middleware/common.py", line 88, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/account/change-password/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
Internal Server Error: /account/change-password
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/middleware/common.py", line 88, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/account/change-password/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
Not Found: /favicon.ico
Internal Server Error: /account/change-password
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/middleware/common.py", line 88, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via PUT, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PUT data. Change your form to point to localhost:8000/account/change-password/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
Internal Server Error: /account/change-password/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/generics.py", line 226, in put
    return self.update(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/mixins.py", line 65, in update
    instance = self.get_object()
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/generics.py", line 88, in get_object
    assert lookup_url_kwarg in self.kwargs, (
AssertionError: Expected view ChangePasswordView to be called with a URL keyword argument named "pk". Fix your URL conf, or set the `.lookup_field` attribute on the view correctly.
Internal Server Error: /account/change-password/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 153, in put
    serializer = self.serializer_class(self.get_object(), data=request.data, partial=True)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/generics.py", line 88, in get_object
    assert lookup_url_kwarg in self.kwargs, (
AssertionError: Expected view ChangePasswordView to be called with a URL keyword argument named "pk". Fix your URL conf, or set the `.lookup_field` attribute on the view correctly.
Internal Server Error: /account/change-password/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 162, in put
    if serializer.is_valid():
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 485, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 80, in validate_old_password
    user = self.context['request'].user
KeyError: 'request'
Internal Server Error: /account/change-password/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 161, in put
    if serializer.is_valid():
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 485, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 80, in validate_old_password
    user = self.context['request'].user
KeyError: 'request'
Internal Server Error: /account/change-password/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 161, in put
    if serializer.is_valid():
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 485, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 80, in validate_old_password
    user = self.context['request'].user
KeyError: 'request'
Internal Server Error: /account/change-password/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 161, in put
    if serializer.is_valid():
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 485, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 80, in validate_old_password
    user = self.context['request'].user
KeyError: 'request'
Internal Server Error: /account/change-password/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 161, in put
    if serializer.is_valid():
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 485, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 80, in validate_old_password
    user = self.context['user']
KeyError: 'user'
Internal Server Error: /account/change-password/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 161, in put
    if serializer.is_valid():
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 485, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 81, in validate_old_password
    user = self.context['request']
KeyError: 'request'
Internal Server Error: /account/change-password/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/request.py", line 416, in __getattr__
    return getattr(self._request, attr)
AttributeError: 'WSGIRequest' object has no attribute 'check_password'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/generics.py", line 226, in put
    return self.update(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 485, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 81, in validate_old_password
    if not user.check_password(value):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/request.py", line 418, in __getattr__
    return self.__getattribute__(attr)
AttributeError: 'Request' object has no attribute 'check_password'
Bad Request: /account/change-password/
Internal Server Error: /account/change-password/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 161, in put
    if serializer.is_valid():
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 485, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 80, in validate_old_password
    user = self.context['request'].user
KeyError: 'request'
Internal Server Error: /account/change-password/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 158, in put
    if serializer.is_valid():
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 485, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 80, in validate_old_password
    user = self.context['request'].user
KeyError: 'request'
Internal Server Error: /account/change-password/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 165, in put
    if serializer.is_valid():
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 485, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 80, in validate_old_password
    user = self.context['request'].user
KeyError: 'request'
Internal Server Error: /account/change-password/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 160, in put
    if serializer.is_valid():
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 485, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 87, in validate_old_password
    user = self.context['request'].user
KeyError: 'request'
Internal Server Error: /account/change-password/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 163, in put
    if serializer.is_valid():
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 485, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 87, in validate_old_password
    user = self.context['request'].user
KeyError: 'request'
Internal Server Error: /account/change-password/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 163, in put
    if serializer.is_valid():
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 485, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 89, in validate_old_password
    if not user.check_password(value):
AttributeError: 'str' object has no attribute 'check_password'
Internal Server Error: /account/change-password/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 163, in put
    if serializer.is_valid():
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 485, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 90, in validate_old_password
    if not user.check_password(value):
AttributeError: 'str' object has no attribute 'check_password'
Internal Server Error: /account/change-password/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 163, in put
    if serializer.is_valid():
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 485, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 84, in validate_old_password
    user = request.user
AttributeError: 'NoneType' object has no attribute 'user'
Internal Server Error: /account/change-password/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 163, in put
    if serializer.is_valid():
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 485, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 87, in validate_old_password
    user = request.user
AttributeError: 'NoneType' object has no attribute 'user'
Internal Server Error: /account/change-password/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 163, in put
    if serializer.is_valid():
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 485, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 87, in validate_old_password
    user = self.context['request'].user
KeyError: 'request'
Internal Server Error: /account/change-password/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 165, in put
    if serializer.is_valid():
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 485, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 87, in validate_old_password
    user = self.context['request'].user
KeyError: 'request'
Internal Server Error: /account/change-password/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 165, in put
    if serializer.is_valid():
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 485, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 87, in validate_old_password
    user = self.context['request'].user
KeyError: 'request'
Internal Server Error: /account/change-password/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 165, in put
    if serializer.is_valid():
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 485, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 87, in validate_old_password
    user = self.context['request'].user
KeyError: 'request'
Internal Server Error: /account/change-password/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 165, in put
    if serializer.is_valid():
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 485, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 87, in validate_old_password
    user = self.context['request'].user
KeyError: 'request'
Internal Server Error: /account/change-password/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 165, in put
    if serializer.is_valid():
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 485, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 88, in validate_old_password
    user = self.context['request'].user
KeyError: 'request'
Internal Server Error: /account/change-password/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 165, in put
    if serializer.is_valid():
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 485, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 88, in validate_old_password
    user = self.context['request'].user
KeyError: 'request'
Internal Server Error: /account/change-password/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 166, in put
    if serializer.is_valid():
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 485, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 88, in validate_old_password
    user = self.context['request'].user
KeyError: 'request'
Internal Server Error: /account/change-password/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/account/views_v1.py", line 166, in put
    if serializer.is_valid():
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 485, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/home/michaellyon/python_projects/payskul/account/serializers.py", line 88, in validate_old_password
    user = self.context['request'].user
KeyError: 'request'
Bad Request: /account/change-password/
Bad Request: /account/change-password/
Not Found: /favicon.ico
Internal Server Error: /core/transactions/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/generics.py", line 239, in get
    return self.list(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/michaellyon/python_projects/payskul/core/views_v1.py", line 161, in get_queryset
    Transaction.objects.all(user=self.request.user)
TypeError: all() got an unexpected keyword argument 'user'
Internal Server Error: /core/transactions/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/pagination.py", line 525, in get_count
    return queryset.count()
AttributeError: 'NoneType' object has no attribute 'count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/generics.py", line 239, in get
    return self.list(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/mixins.py", line 40, in list
    page = self.paginate_queryset(queryset)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/generics.py", line 171, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/pagination.py", line 387, in paginate_queryset
    self.count = self.get_count(queryset)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/pagination.py", line 527, in get_count
    return len(queryset)
TypeError: object of type 'NoneType' has no len()
Internal Server Error: /core/transactions/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/pagination.py", line 525, in get_count
    return queryset.count()
AttributeError: 'NoneType' object has no attribute 'count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/generics.py", line 239, in get
    return self.list(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/mixins.py", line 40, in list
    page = self.paginate_queryset(queryset)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/generics.py", line 171, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/pagination.py", line 387, in paginate_queryset
    self.count = self.get_count(queryset)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/pagination.py", line 527, in get_count
    return len(queryset)
TypeError: object of type 'NoneType' has no len()
Unauthorized: /core/transactions/
Internal Server Error: /core/transactions/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 2018, in get_prep_value
    return int(value)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/contrib/auth/models.py", line 437, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/generics.py", line 239, in get
    return self.list(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/michaellyon/python_projects/payskul/core/views_v1.py", line 161, in get_queryset
    return Transaction.objects.filter(user=self.request.user)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 2020, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x7f451a0189d0>.
Internal Server Error: /core/transactions/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 2018, in get_prep_value
    return int(value)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/contrib/auth/models.py", line 437, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/generics.py", line 239, in get
    return self.list(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/michaellyon/python_projects/payskul/core/views_v1.py", line 161, in get_queryset
    return Transaction.objects.filter(user=self.request.user)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 2020, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x7f451a0885b0>.
Internal Server Error: /core/transactions/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 2018, in get_prep_value
    return int(value)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/contrib/auth/models.py", line 437, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/generics.py", line 239, in get
    return self.list(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/michaellyon/python_projects/payskul/core/views_v1.py", line 161, in get_queryset
    return Transaction.objects.filter(user=self.request.user)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 2020, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x7f451a018ee0>.
Internal Server Error: /core/transactions/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 2018, in get_prep_value
    return int(value)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/contrib/auth/models.py", line 437, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/generics.py", line 239, in get
    return self.list(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/michaellyon/python_projects/payskul/core/views_v1.py", line 161, in get_queryset
    return Transaction.objects.filter(user=self.request.user)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 2020, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x7f45186706a0>.
Not Found: /favicon.ico
Not Found: /favicon.ico
Bad Request: /account/change-password/
Bad Request: /account/change-password/
Internal Server Error: /core/transactions/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/renderers.py", line 99, in render
    ret = json.dumps(
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type method is not JSON serializable
Internal Server Error: /core/transactions/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/generics.py", line 239, in get
    return self.list(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
  File "/home/michaellyon/python_projects/payskul/core/serializers.py", line 24, in get_total_payments
    return obj.get_total_payments()
  File "/home/michaellyon/python_projects/payskul/core/models.py", line 86, in get_total_payments
    loan = Loan.get_loan(self.user)
TypeError: get_loan() missing 1 required positional argument: 'user'
Internal Server Error: /core/transactions/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/generics.py", line 239, in get
    return self.list(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
  File "/home/michaellyon/python_projects/payskul/core/serializers.py", line 24, in get_total_payments
    return obj.get_total_payments()
  File "/home/michaellyon/python_projects/payskul/core/models.py", line 87, in get_total_payments
    loan = Loan.get_loan(self.user)
TypeError: get_loan() takes 1 positional argument but 2 were given
Internal Server Error: /core/transactions/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/generics.py", line 239, in get
    return self.list(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
  File "/home/michaellyon/python_projects/payskul/core/serializers.py", line 24, in get_total_payments
    return obj.get_total_payments()
  File "/home/michaellyon/python_projects/payskul/core/models.py", line 90, in get_total_payments
    total = Transaction.objects.filter(loan=loan, user=self.user, type="FR").aggregate(Sum('amount'))
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/fields/related_lookups.py", line 168, in get_prep_lookup
    return super().get_prep_lookup()
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/db/models/lookups.py", line 337, in get_prep_lookup
    raise ValueError(
ValueError: The QuerySet value for an exact lookup must be limited to one result using slicing.
Internal Server Error: /core/transactions/
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/generics.py", line 239, in get
    return self.list(request, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
  File "/home/michaellyon/python_projects/payskul/core/serializers.py", line 24, in get_total_payments
    return obj.get_total_payments()
  File "/home/michaellyon/python_projects/payskul/core/models.py", line 91, in get_total_payments
    return total['ammount__sum'] or 0 if not total["ammount__sum"] else total["ammount__sum"]
KeyError: 'ammount__sum'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michaellyon/python_projects/payskul/apiv1/views.py", line 6, in home
    return render(request, "apiv1/docs.html")
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/template/defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/michaellyon/python_projects/payskul/env/lib/python3.9/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'change_password' not found. 'change_password' is not a valid view function or pattern name.
Not Found: /favicon.ico
